# Generated by Django 5.2.17 on 2026-10-02 10:26

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shot_number', models.CharField(max_length=32)),
                ('shot_type', models.CharField(blank=True, max_length=64)),
                ('lens', models.CharField(blank=True, max_length=64)),
                ('storyboard_url', models.URLField(blank=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('avatar', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='core.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('rank', models.CharField(db_index=True, default='0|h:', max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.workspace')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='ShotBlockCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shot')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workspacenode')),
            ],
            options={
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='shot',
            name='blocks',
            field=models.ManyToManyField(related_name='covered_by_shots', through='core.ShotBlockCoverage', to='core.workspacenode'),
        ),
        migrations.AddField(
            model_name='shot',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='core.workspacenode'),
        ),
        migrations.AddIndex(
            model_name='workspacenode',
            index=models.Index(fields=['workspace', 'parent', 'rank'], name='core_worksp_workspa_80bc85_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacenode',
            index=models.Index(fields=['workspace', 'type'], name='core_worksp_workspa_3fd5cf_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacenode',
            index=django.contrib.postgres.indexes.GinIndex(fields=['properties'], name='core_worksp_propert_cc1c6c_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='shotblockcoverage',
            unique_together={('shot', 'block')},
        ),
    ]
