# Generated by Django 5.2.17 on 2026-10-02 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shot',
            name='storyboard_file',
            field=models.FileField(blank=True, null=True, upload_to='storyboards/'),
        ),
        migrations.CreateModel(
            name='BreakdownElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('PROP', 'Prop'), ('COSTUME', 'Costume'), ('VFX', 'VFX'), ('SFX', 'SFX'), ('LOCATION', 'Location'), ('VEHICLE', 'Vehicle'), ('MAKEUP', 'Makeup')], max_length=32)),
                ('name', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blocks', models.ManyToManyField(blank=True, related_name='breakdown_elements', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown_elements', to='core.workspace')),
            ],
        ),
    ]
