# Generated by Django 5.2.17 on 2026-10-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shot_storyboard_file_breakdownelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspacenode',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacenode',
            name='revision_asterisk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspacenode',
            name='revision_color',
            field=models.CharField(choices=[('WHITE', 'White'), ('BLUE', 'Blue'), ('PINK', 'Pink'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('GOLDENROD', 'Goldenrod'), ('BUFF', 'Buff'), ('SALMON', 'Salmon'), ('CHERRY', 'Cherry')], default='WHITE', max_length=32),
        ),
    ]
