# Generated by Django 5.2.17 on 2026-10-02 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workspacenode_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('revision_color', models.CharField(choices=[('WHITE', 'White'), ('BLUE', 'Blue'), ('PINK', 'Pink'), ('YELLOW', 'Yellow'), ('GREEN', 'Green'), ('GOLDENROD', 'Goldenrod'), ('BUFF', 'Buff'), ('SALMON', 'Salmon'), ('CHERRY', 'Cherry')], default='WHITE', max_length=32)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['document_node', 'created_at'], name='core_docume_documen_53a5ca_idx')],
            },
        ),
    ]
