# Generated by Django 5.2.17 on 2026-10-02 16:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_documentsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShootingSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Principal Photography', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShootingDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('call_time', models.CharField(default='07:00 AM', max_length=30)),
                ('shooting_location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='core.shootingschedule')),
            ],
            options={
                'ordering': ['order', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='StripboardItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_banner', models.BooleanField(default=False)),
                ('banner_title', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strip_items', to='core.workspacenode')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strips', to='core.shootingschedule')),
                ('shooting_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strips', to='core.shootingday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
