# Generated by Django 5.2.17 on 2026-10-02 16:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_shootingschedule_shootingday_stripboarditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionTake',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('take_number', models.PositiveIntegerField(default=1)),
                ('is_circle_take', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('FALSE_START', 'False Start')], default='COMPLETE', max_length=30)),
                ('camera_roll', models.CharField(blank=True, max_length=50)),
                ('sound_roll', models.CharField(blank=True, max_length=50)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takes', to='core.shot')),
            ],
            options={
                'ordering': ['take_number'],
                'indexes': [models.Index(fields=['shot', 'take_number'], name='core_produc_shot_id_98061c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScriptNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=120)),
                ('author_role', models.CharField(default='WRITER', max_length=60)),
                ('category', models.CharField(choices=[('CREATIVE', 'Creative'), ('LEGAL', 'Legal'), ('CONTINUITY', 'Continuity'), ('PRODUCTION', 'Production'), ('DIRECTOR', 'Director')], default='CREATIVE', max_length=60)),
                ('text', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.workspacenode')),
                ('parent_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.scriptnote')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='script_notes', to='core.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['node', 'created_at'], name='core_script_node_id_d0579e_idx')],
            },
        ),
    ]
