# Generated by Django 5.2.17 on 2026-10-02 17:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productiontake_scriptnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADRCue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cue_number', models.CharField(max_length=30)),
                ('reason', models.CharField(choices=[('NOISE', 'Noise / Audio Issue'), ('PERFORMANCE', 'Performance / Delivery'), ('LINE_CHANGE', 'Line Change / Alt Take'), ('TV_CLEAN', 'TV Clean / Censorship'), ('ACCENT', 'Accent / Diction'), ('OTHER', 'Other')], default='NOISE', max_length=50)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('STANDARD', 'Standard'), ('OPTIONAL', 'Optional')], default='STANDARD', max_length=30)),
                ('status', models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('SCHEDULED', 'Scheduled'), ('RECORDED', 'Recorded'), ('APPROVED', 'Approved'), ('OMITTED', 'Omitted')], default='NEEDS_REVIEW', max_length=30)),
                ('timecode_in', models.CharField(blank=True, default='01:00:00:00', max_length=30)),
                ('timecode_out', models.CharField(blank=True, default='01:00:05:00', max_length=30)),
                ('actor_notes', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='adr_takes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adr_cues', to='core.character')),
                ('dialogue_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adr_cues', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adr_cues', to='core.workspace')),
            ],
            options={
                'ordering': ['cue_number', 'created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='core_adrcue_workspa_bb2406_idx'), models.Index(fields=['dialogue_node'], name='core_adrcue_dialogu_d8105d_idx'), models.Index(fields=['character'], name='core_adrcue_charact_140d65_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioSpottingCue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cue_type', models.CharField(choices=[('SCORE', 'Score / Score Music'), ('SOURCE_MUSIC', 'Source Music / Diegetic'), ('FOLEY', 'Foley'), ('SFX', 'Sound Effects'), ('AMBIENCE', 'Environmental Ambience')], default='SCORE', max_length=50)),
                ('cue_name', models.CharField(max_length=150)),
                ('timecode_in', models.CharField(blank=True, max_length=30)),
                ('timecode_out', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('intensity', models.CharField(choices=[('LOW', 'Low / Subtle'), ('MEDIUM', 'Medium'), ('HIGH', 'High / Energetic'), ('CLIMACTIC', 'Climactic / Dramatic')], default='MEDIUM', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_spotting_cues', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_spotting_cues', to='core.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace', 'cue_type'], name='core_audios_workspa_378ad3_idx'), models.Index(fields=['scene'], name='core_audios_scene_i_c82deb_idx')],
            },
        ),
    ]
