# Generated by Django 5.2.17 on 2026-10-03 05:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_adrcue_audiospottingcue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Production Budget - Master Draft', max_length=255)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('contingency_percentage', models.FloatField(default=10.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('screenplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('tier', models.CharField(choices=[('ATL', 'Above-The-Line (ATL)'), ('BTL_PRODUCTION', 'Below-The-Line Production (BTL)'), ('BTL_POST', 'Below-The-Line Post-Production (BTL)'), ('OTHER', 'Other / General & Administrative')], default='BTL_PRODUCTION', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.productionbudget')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_code', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('rate_type', models.CharField(choices=[('FLAT', 'Flat Rate'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('HOURLY', 'Hourly'), ('PER_UNIT', 'Per Unit')], default='DAILY', max_length=30)),
                ('quantity', models.FloatField(default=1.0)),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('fringe_percentage', models.FloatField(default=0.0)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('breakdown_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='core.breakdownelement')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='core.budgetcategory')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='core.character')),
            ],
            options={
                'ordering': ['account_code'],
                'indexes': [models.Index(fields=['category', 'account_code'], name='core_budget_categor_77f224_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productionbudget',
            index=models.Index(fields=['workspace', 'screenplay'], name='core_produc_workspa_71f724_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetcategory',
            index=models.Index(fields=['budget', 'tier'], name='core_budget_budget__6054ed_idx'),
        ),
    ]
