# Generated by Django 5.2.17 on 2026-10-03 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productionbudget_budgetcategory_budgetlineitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('DEVELOPMENT', 'Development'), ('PRE_PRODUCTION', 'Pre-Production'), ('PRODUCTION', 'Production'), ('POST_PRODUCTION', 'Post-Production'), ('DELIVERY', 'Delivery & Distribution')], default='PRODUCTION', max_length=60)),
                ('title', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DELAYED', 'Delayed')], default='IN_PROGRESS', max_length=30)),
                ('progress_percentage', models.PositiveIntegerField(default=0)),
                ('department', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.workspace')),
            ],
            options={
                'ordering': ['order', 'start_date', 'created_at'],
                'indexes': [models.Index(fields=['workspace', 'screenplay'], name='core_produc_workspa_20ec98_idx'), models.Index(fields=['phase'], name='core_produc_phase_fe63d7_idx')],
            },
        ),
    ]
