# Generated by Django 5.2.17 on 2026-10-03 05:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productionmilestone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('OWNER', 'Studio Executive / Owner'), ('PRODUCER', 'Producer'), ('DIRECTOR', 'Director'), ('WRITER', 'Writer'), ('DEPT_HEAD', 'Head of Department'), ('ACTOR', 'Actor')], default='WRITER', max_length=40)),
                ('department', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workspace_memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.workspace')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['workspace', 'email'], name='core_worksp_workspa_bf5230_idx'), models.Index(fields=['workspace', 'role'], name='core_worksp_workspa_a9e3d9_idx')],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'email'), name='unique_workspace_membership_email')],
            },
        ),
    ]
