# Generated by Django 5.2.17 on 2026-10-03 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workspacemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=150)),
                ('actor_role', models.CharField(default='WRITER', max_length=40)),
                ('action_type', models.CharField(max_length=60)),
                ('department', models.CharField(default='SCRIPT', max_length=60)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='core_studio_workspa_19c7b0_idx'), models.Index(fields=['workspace', 'department'], name='core_studio_workspa_c2fce9_idx'), models.Index(fields=['workspace', 'action_type'], name='core_studio_workspa_19a606_idx')],
            },
        ),
    ]
