# Generated by Django 5.2.17 on 2026-10-03 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_studioactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptCoverageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('logline', models.TextField()),
                ('verdict', models.CharField(choices=[('RECOMMEND', 'Recommend'), ('CONSIDER', 'Consider'), ('PASS', 'Pass')], default='CONSIDER', max_length=30)),
                ('commercial_viability', models.PositiveIntegerField(default=75)),
                ('character_score', models.PositiveIntegerField(default=80)),
                ('pacing_score', models.PositiveIntegerField(default=70)),
                ('synopsis', models.TextField()),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('production_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenplay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_reports', to='core.workspacenode')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_reports', to='core.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', '-created_at'], name='core_script_workspa_686513_idx'), models.Index(fields=['screenplay', '-created_at'], name='core_script_screenp_f22012_idx'), models.Index(fields=['verdict'], name='core_script_verdict_da10cc_idx')],
            },
        ),
    ]
