# Generated by Django 5.2.17 on 2026-10-03 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_scriptcoveragereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacenode',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_nodes', to='core.workspace'),
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(default='universalNode', max_length=64)),
                ('title', models.CharField(default='Untitled Node', max_length=128)),
                ('category', models.CharField(default='default', max_length=64)),
                ('position_x', models.FloatField(default=100.0)),
                ('position_y', models.FloatField(default=100.0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_collapsed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='core.workspace')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('source_handle', models.CharField(blank=True, max_length=64, null=True)),
                ('target_handle', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='core.workspace')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='core.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='core.node')),
            ],
        ),
    ]
