# Generated by Django 5.2.17 on 2026-10-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_scriptcoveragereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studioactivitylog',
            name='actor_role',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.DeleteModel(
            name='WorkspaceMembership',
        ),
    ]
