# Generated by Django 5.2.17 on 2026-10-03 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_workspacenode_workspace_node_edge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='viewport_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='WorkspaceEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('scene_heading', 'Scene Heading'), ('action', 'Action'), ('character', 'Character'), ('dialogue', 'Dialogue'), ('parenthetical', 'Parenthetical'), ('ai_prompt', 'AI Prompt'), ('storyboard', 'Storyboard Frame'), ('note', 'Note')], default='dialogue', max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('order_index', models.IntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='core.workspace')),
            ],
            options={
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canvas_nodes', to='core.workspaceentity'),
        ),
    ]
