# Generated by Django 5.2.17 on 2026-10-04 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_studioactivitylog_actor_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workspace',
            name='project_type',
            field=models.CharField(choices=[('film', 'Film Studio'), ('novel', 'Novel Studio'), ('article', 'Codex / Article')], default='film', max_length=32),
        ),
    ]
